before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: KZs2G4hJNJspqVjxvCX/bc4a7CJKpWDZp6YjIxnrc/1I7rP0yssAqZdf9g53dR2WveWvzis5Xo3we+TJQOQYtFYS2rE/LyzBTaZdydaAKSfK8xYnveahkIEkD7fICSmjwXVJRYUc14Dr+nqq8WMJyGGA244md2omXNSpMuoYh5LFb9Xey8ShsbQD0Emw3dz9QHBlppwWnIY0KMKIjLniSr9Kej+IMQDgMdkWfs6vBD23SRhg1djkdON8r9LOLWAa6QqK7OKLxn6gICAa0ROYkHCedplIGiAK/TXrUR/LOy1B9sakK7Qnm9zu1027EqFugpQQIm7GvFGon/o+td4xKzNaU+Ut7UL4X2SwNvq4njStOdEvRbHknu9BC+PZ6cP2kYy84MHRY7lkcyCLQ4AtdezWoogPl33eeDQsGt8/jd8vpZNXrU9lIUe4fQxbFt8Jiqmwv8NvZknDQ+nobc81+DdYhSRlocuQKb4uCgxo1H4MMuI6elSV9BZJWOgh1uYOYHgzu2EwN+Ig5v3SsIxlvbk97bCo8ydQVGlzFa9wZKrN0m0W+5pZOxg9JSklFBH72fySvovxkQf3m5hKD+1MKkIF2NDkkDj01PLGRUZaOVDw2PzHXZVdJLpDYun32TPfc99Keh6ol2wmgpD516RyDrwMpdCUWSPYOxwHcn8pM4A= # CRYPTO_AES_KEY
language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
